name: Java Style

on:
  pull_request:
    branches: [ master ]

jobs:
  check-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Java JDK
      uses: actions/setup-java@v1.3.0
      with:
        java-version: 12

    - name: Run java checkstyle
      uses: nikitasavinov/checkstyle-action@0.2.0
